---
title: "Saluscare Dashboard"
format:
  dashboard:
    theme: cosmo
    #scrolling: true
execute:
  echo: false
---

```{r library, include=FALSE}
library(tidyverse)
library(data.table)
library(reactable)

```

## Data Overview

```{r Data Overview | setup, include=FALSE}
list_column <- readRDS("/home/rstudio/Data/object/list_column.rds")
```


```{r Data Overview | layout}
#| title: 데이터 종류별 변수

f_style1 <- function(value) { if ((value %% 64 == 0) & (value != 0)) { list(fontWeight = "bold") } else if (value != 0) { list() } else { list() } }

f_style2 <- function(value) { if (value == 64) { list(color = "green", fontWeight = "bold") } else if (value != 0) { list(color = "red") } else { list() } }

reactable(
  list_column$layout %>% select(COLUMN, 비고, AINQ:RSLT, starts_with("N_")),
  filterable = TRUE, sortable = TRUE,
  columns = list(
    N_ALL  = colDef(style = f_style1),
    N_AINQ = colDef(style = f_style2),
    N_JUDD = colDef(style = f_style2),
    N_RSLT = colDef(style = f_style2),
    COLUMN = colDef(name = "Column"),
    비고   = colDef(name = "비고"),
    AINQ   = colDef(name = "AINQ"),
    JUDD   = colDef(name = "JUDD"),
    RSLT   = colDef(name = "RSLT")
  )
)
```

```{r Data Overview | codebook}
#| title: 코드북

library(bslib)
library(htmltools)
library(shiny)

f_reactable <- function(x, columns = columns){
  reactable(x, columns = columns, filterable = TRUE, sortable = TRUE)
}

df <- list_column$codebook

tabsetPanel(
  tabPanel("건진상세", 
           f_reactable(df[[2]] %>% 
                       select(HEALEXAMDETLFLAG, DETLDESC),
                     columns = list(HEALEXAMDETLFLAG = 
                                    colDef(style = list(fontWeight = "bold")
                                           )
                                    )
                     )
           ),
  tabPanel("검사코드",
           f_reactable(df[[3]] %>% 
                       select(TESTCD, TESTNM, LRFLAG, everything()),
                     columns = list(TESTCD =
                                      colDef(style = list(fontWeight = "bold")
                                             )
                                    )
                     )
           ),
  tabPanel("처방코드",
           f_reactable(df[[4]] %>% 
                         select(PRCPCD, PRCPNM, FROMDD, TODD, everything()),
                       columns = list(PRCPCD =
                                      colDef(style = list(fontWeight = "bold")
                                             )
                                    )
                       )
           ),
  tabPanel("문진분류",
           f_reactable(df[[5]] %>% 
                         select(INQRFLAG, CDNAME, FROMDD, TODD, everything()),
                       columns = list(INQRFLAG =
                                      colDef(style = list(fontWeight = "bold")
                                             )
                                    )
                       ))
  )

```

## 
