
---
format: dashboard
---

<script>
document.addEventListener('DOMContentLoaded', (event) => {
  document.getElementById('nav-data-overview').classList.add('active');
});
</script>

```{r setup, include=FALSE}
source("library.R")
```

```{r data, include=FALSE}
list_column <- readRDS("/home/rstudio/Data/object/list_column.rds")
```

# Layout

```{r data-1}
df_layout <- list_column$layout
```

::: {.panel-tabset}

## 전체

```{r reactable-1}
df_layout %>% 
  select(COLUMN, 비고, AINQ:RSLT, starts_with("N_")) %>% 
  mutate(COLUMN = gsub("\\(.*\\)","",COLUMN)) %>%
  f_reactable(
    columns = list(COLUMN = colDef(name = "Column", style = f_style_bold),
                   비고   = colDef(name = "비고"),
                   AINQ   = colDef(name = "AINQ"),
                   JUDD   = colDef(name = "JUDD"),
                   RSLT   = colDef(name = "RSLT"),
                   N_ALL  = colDef(style = f_style1),
                   N_AINQ = colDef(style = f_style2),
                   N_JUDD = colDef(style = f_style2),
                   N_RSLT = colDef(style = f_style2)
  ),
  pagination=FALSE,
  wrap=FALSE
)
```

## AINQ
```{r}
df_layout %>%
  filter(AINQ == "O") %>%
  select(COLUMN, 비고, AINQ:RSLT, starts_with("N_")) %>% 
  mutate(COLUMN = gsub("\\(.*\\)","",COLUMN)) %>%
  f_reactable(
    columns = list(COLUMN = colDef(name = "Column", style = f_style_bold),
                   비고   = colDef(name = "비고"),
                   AINQ   = colDef(name = "AINQ"),
                   JUDD   = colDef(name = "JUDD"),
                   RSLT   = colDef(name = "RSLT"),
                   N_ALL  = colDef(style = f_style1),
                   N_AINQ = colDef(style = f_style2),
                   N_JUDD = colDef(style = f_style2),
                   N_RSLT = colDef(style = f_style2)
  ),
  pagination=FALSE,
  wrap=FALSE
)
```

## JUDD
```{r}
df_layout %>%
  filter(JUDD == "O") %>%
  select(COLUMN, 비고, AINQ:RSLT, starts_with("N_")) %>% 
  mutate(COLUMN = gsub("\\(.*\\)","",COLUMN)) %>%
  f_reactable(
    columns = list(COLUMN = colDef(name = "Column", style = f_style_bold),
                   비고   = colDef(name = "비고"),
                   AINQ   = colDef(name = "AINQ"),
                   JUDD   = colDef(name = "JUDD"),
                   RSLT   = colDef(name = "RSLT"),
                   N_ALL  = colDef(style = f_style1),
                   N_AINQ = colDef(style = f_style2),
                   N_JUDD = colDef(style = f_style2),
                   N_RSLT = colDef(style = f_style2)
  ),
  pagination=FALSE,
  wrap=FALSE
)
```
## RSLT
```{r}
df_layout %>%
  filter(RSLT == "O") %>%
  select(COLUMN, 비고, AINQ:RSLT, starts_with("N_")) %>% 
  mutate(COLUMN = gsub("\\(.*\\)","",COLUMN)) %>%
  f_reactable(
    columns = list(COLUMN = colDef(name = "Column", style = f_style_bold),
                   비고   = colDef(name = "비고"),
                   AINQ   = colDef(name = "AINQ"),
                   JUDD   = colDef(name = "JUDD"),
                   RSLT   = colDef(name = "RSLT"),
                   N_ALL  = colDef(style = f_style1),
                   N_AINQ = colDef(style = f_style2),
                   N_JUDD = colDef(style = f_style2),
                   N_RSLT = colDef(style = f_style2)
  ),
  pagination=FALSE,
  wrap=FALSE
)
```
:::

# PACS

```{r data-2, include=FALSE}
df_pacs <- read_csv("/home/rstudio/Data/meta/240729_PACS 비정형 데이터 보유 현황_살루스케어.csv")

df_pacs <- df_pacs %>%
  mutate(MODALITY = case_when(`검사 유형`!=`검사구분(MODALITY)` ~ paste0(`검사 유형`," (",`검사구분(MODALITY)`,")"),
                              TRUE ~ .$`검사 유형`),
         `용량(GB)` = as.integer(`용량(GB)`))
```

::: {.panel-tabset}

## MODALITY

::: {.panel-tabset}

### 전체

```{r}
df_pacs %>%
  select(-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique"),
      `건 수` = colDef(aggregate = "sum"),
      `용량(GB)` = colDef(aggregate = "sum")
    ),
    groupBy = c("MODALITY","검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```


### 복부 외 초음파 (US)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'US') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### CT

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'CT') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### MRI/MRA (MR)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'MR') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 유방촬영 외 X-ray (DR)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'DR') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 내시경 (ES)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'ES') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    groupBy = c("검사명１"),
    pagination=FALSE
  )
```

### 골밀도 (OT)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'OT') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### PET CT (PT)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'PT') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 심전도 (EK)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'EK') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 유방촬영 (MG)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'MG') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 위장조영 (RF)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'RF') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 동맥경화도 (VS)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'VS') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### 안저안압 (XC)

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'XC') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### EKG

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'EKG') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

### OP

```{r}
df_pacs %>%
  filter(`검사구분(MODALITY)` == 'OP') %>%
  select(-"검사구분(MODALITY)",-"검사 유형",-MODALITY) %>%
  f_reactable(
    columns = list(
      SALUS_CENTER = colDef(aggregate = "unique")
    ),
    groupBy = c("검사명１"),
    pagination=FALSE,
    wrap = FALSE
  )
```

:::

## CENTER

::: {.panel-tabset}

### 본원

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '본원') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```

### 여의도

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '여의도') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```

### 강남

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '강남') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```

### 수원

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '수원') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```

### 대구

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '대구') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```

### 부산

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '부산') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```

### 광주

```{r}
df_pacs %>%
  filter(SALUS_CENTER == '광주') %>%
  select(-SALUS_CENTER,-"검사구분(MODALITY)",-"검사 유형") %>%
  f_reactable(
  groupBy = c('MODALITY'),
  pagination=FALSE
  )
```



:::

:::

